// File: mac_llm_B.v
// Generated by: ChatGPT-4o
module mac (
    input  logic               clk,
    input  logic               rst,   // active-high synchronous reset
    input  logic signed [7:0]  a,
    input  logic signed [7:0]  b,
    output logic signed [31:0] out
);
    // Intermediate product (16-bit signed is sufficient for 8x8 multiply)
    logic signed [15:0] mult;
    always_ff @(posedge clk) begin
        if (rst) begin
            out <= 32'sd0;
        end else begin
            mult = a * b;                 // signed multiplication
            out  <= out + {{16{mult[15]}}, mult}; // sign-extend to 32 bits
        end
    end
endmodule
