SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/binary_conv.sv
COCOTB_TOPLEVEL = binary_conv
COCOTB_TEST_MODULES = tb_binary_conv
ICARUS_BIN_DIR = /opt/homebrew/bin

include $(shell cocotb-config --makefiles)/Makefile.sim
