SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/mac_correct.v
COCOTB_TOPLEVEL = mac
COCOTB_TEST_MODULES = test_mac
ICARUS_BIN_DIR = /opt/homebrew/bin

include $(shell cocotb-config --makefiles)/Makefile.sim
